apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubey-ui
  name: kubey-ui
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kubey-ui
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubey-ui
  name: kubey-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubey-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubey-ui
    spec:
      containers:
        - image: quay.io/internetofsteve/kubey-ui:latest
          imagePullPolicy: Always
          name: kubey-ui
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubey-ui
spec:
  tls:
    - secretName: steve-dev-dius-cert
  rules:
  - host: steve.dev.dius.com.au
    http:
      paths:
      - path: /
        backend:
          serviceName: kubey-ui
          servicePort: 80