version: 2.1
executors:
  default:
    docker:
    - image: circleci/node:8.11
    working_directory: ~/code
    environment:
      CI: "true"
jobs:
  build:
    executor: default
    steps:
    - checkout
    - setup_remote_docker
    - run: |
        rm -rf build && \
        yarn && \
        yarn test && \
        yarn build && \
        echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin quay.io && \
        docker build -t quay.io/internetofsteve/kubey-ui:${CIRCLE_SHA1} . && \
        docker build -t quay.io/internetofsteve/kubey-ui:latest . && \
        docker push quay.io/internetofsteve/kubey-ui:${CIRCLE_SHA1} && \
        docker push quay.io/internetofsteve/kubey-ui:latest
    - persist_to_workspace:
        root: ~/
        paths:
        - code

  deploy-to-staging:
    executor: default
    steps:
    - attach_workspace:
        at: ~/
    - run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl && \
        chmod +x kubectl && \
        echo $KUBE_CERT | base64 --decode > ca.crt && \
        sed -i -e 's/$IMAGE_VERSION/'${CIRCLE_SHA1}'/g' kube.yml && \
        ./kubectl --kubeconfig /dev/null \
        --server $KUBE_SERVER \
        --certificate-authority ca.crt \
        --token $(echo $KUBE_TOKEN | base64 --decode) \
        apply -f kube.yml && \
         ./kubectl --kubeconfig /dev/null \
        --server $KUBE_SERVER \
        --certificate-authority ca.crt \
        --token $(echo $KUBE_TOKEN | base64 --decode) \
        rollout status deployment/kubey-ui
  deploy-to-prod:
    executor: default
    steps:
    - attach_workspace:
        at: ~/
    - run: |
        echo "Running kube deploy"

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build:
        context: kubey-staging
        filters:
          branches:
            only:
            - master
    - deploy-to-staging:
        context: kubey-staging
        requires:
        - build
    - deploy-to-prod-approval:
        type: approval
        requires:
        - deploy-to-staging
    - deploy-to-prod:
        context: kubey-prod
        requires:
        - deploy-to-prod-approval
